In [1]:
import numpy as np

**A markov matrix is a square matrix with only non-negative values and all values in each column adding up to 1**

In [2]:
transition_matrix = np.array([
    [0.3,0.4,0.2],
    [0.5,0.4,0.3],
    [0.2,0.2,0.5],
    ]
)

initial_state_vector = np.array([0,0,1])

In [3]:
X = np.dot(transition_matrix,initial_state_vector)

In [4]:
X

array([0.2, 0.3, 0.5])

Repeating this infinite times makes the state vector approach equilibrium as it becomes an eigenvector with corresponding eigenvalue of 1

In [5]:
for _ in range(20):
    X = np.dot(transition_matrix,X)
    print(X)

[0.28 0.37 0.35]
[0.302 0.393 0.305]
[0.3088 0.3997 0.2915]
[0.31082 0.40173 0.28745]
[0.311428 0.402337 0.286235]
[0.3116102 0.4025193 0.2858705]
[0.31166488 0.40257397 0.28576115]
[0.31168128 0.40259037 0.28572834]
[0.3116862  0.40259529 0.2857185 ]
[0.31168768 0.40259677 0.28571555]
[0.31168812 0.40259721 0.28571467]
[0.31168825 0.40259735 0.2857144 ]
[0.31168829 0.40259739 0.28571432]
[0.31168831 0.4025974  0.2857143 ]
[0.31168831 0.4025974  0.28571429]
[0.31168831 0.4025974  0.28571429]
[0.31168831 0.4025974  0.28571429]
[0.31168831 0.4025974  0.28571429]
[0.31168831 0.4025974  0.28571429]
[0.31168831 0.4025974  0.28571429]


In [6]:
eigvals, eigvecs = np.linalg.eig(transition_matrix)

In [7]:
vec = eigvecs[:,np.where(np.isclose(eigvals,1.0))].reshape(-1)
vec = vec/np.sum(vec)

In [8]:
vec

array([0.31168831, 0.4025974 , 0.28571429])