In [1]:
import numpy as np

In [2]:
def non_zero_in_column(X,row):
    X = X.copy()
    for i in range(row,X.shape[0]):
        if X[i,row] != 0:
            X[i,row], X[row,i] = X[row,i], X[i,row]
            break
    return X

In [3]:
def row_echelon_form(X,augmented=True):
    check = X
    if augmented:
        check = X[:,:-1]
    if np.isclose(np.linalg.det(check),0):
        return 'Singular Matrix'
    X = X.copy()
    rows = X.shape[0]

    for i in range(rows):
        pivot_candidate = X[i,i]
        
        if np.isclose(pivot_candidate,0):
            X = non_zero_in_column(X,i)
        
        pivot = X[i,i]

        X[i,:] = X[i,:] / pivot

        for j in range(i+1,rows):
            if X[j,i] != 0:
                X[j,:] = (X[j,:] / X[j,i]) - X[i,:]

    return X

In [4]:
def backsubstitution(X):
    X = X.copy()
    rows = X.shape[0]
    for i in reversed(range(rows)):
        backsub_row = X[i,:]

        for j in reversed(range(i)):
            X[j,:] = X[j,:] - (backsub_row * X[j,i])
        
    return X

In [5]:
def gaussian_elimination(A,B):
    augmented_matrix = np.hstack((A,B),dtype=np.float32)
    reduced_form = row_echelon_form(augmented_matrix)
    if isinstance(reduced_form,str):
        return reduced_form
    solution_matrix = backsubstitution(reduced_form)

    return solution_matrix[:,-1] 

### **USING THE GAUSSIAN ELIMINATION FUNCTION TO SOLVE SYSTEMS OF EQUATIONS**

<img src='system_1.png' width="500"/>

In [6]:
x = np.array([[1,-2,-1],[3,4,-6],[2,2,-3]])
y = np.array([[2],[-1],[3]])

gaussian_elimination(x,y)

array([7. , 0.5, 4. ], dtype=float32)

<img src='system_2.png' width="500"/>

In [7]:
x = np.array([[1,1,1],[2,1,-1],[3,2,-1]])
y = np.array([[6],[1],[4]])

gaussian_elimination(x,y)

array([0.9999976, 2.0000038, 2.9999986], dtype=float32)

<img src='system_3.png' width="500"/>

In [8]:
x = np.array([[1,1,1],[2,3,5],[4,5,6]])
y = np.array([[6],[19],[28]])

gaussian_elimination(x,y)

array([ 5., -2.,  3.], dtype=float32)